---
title: "Lab 11: Logistic Regression"
author: "Fabio Setti"
institute: "PSYC 6802 - Introduction to Psychology Statistics"
bibliography: Additional files/references.bib
csl: Additional files/apa.csl
title-slide-attributes:
  data-transition: "zoom"
  data-visibility: "uncounted"
format:
   revealjs:
      footer: "PSYC 6802 - Lab 11: Logistic Regression"
      width: 1280
      height: 720
      chalkboard: true
      slide-number: c/t 
      theme: Fabio_theme/Fabio_theme.scss
      navigation-mode: linear
      controls: false
      auto-stretch: false
      header-includes:
        - <script src="Fabio_theme/Fabio_theme.js"></script>

editor: source
build: local
---

## Today's Packages and Data 🤗 

:::: {.columns}
::: {.column width = '50%'}

```{r}
#| code-fold: true
#| eval: false
#| echo: true
#| code-line-numbers: false
#| code-summary: "Install Packages Code"
#| classes: code-125

install.packages("ppcor")
```

```{r}
#| eval: true
#| echo: true
#| code-line-numbers: false
#| warning: false
#| classes: code-150

library(ppcor)
library(tidyverse)
# I am setting a theme for all the plots
theme_set(theme_classic(base_size = 16, accent = "#7a0b80",
                        base_family = 'serif'))

```



::: {.panel-tabset}

### `ppcor`

The `ppcor` package [@Kim_2015a] is is a pretty simple package with a small number of functions. We will use it to compute partial and semi-partial correlations.

:::

:::

::: {.column width = '50%'}
<center style="padding-bottom: 21px;"> [Data]{.data-title} </center>

Today we will look at some data about US states. I chose this subset of variables from a larger dataset that you can find [here](https://github.com/quinix45/Fabio-Setti/blob/main/static/data/Lab_09_States.xlsx){target='_blank'}.
 
```{r}
#| eval: true
#| echo: true 
#| message: false
#| code-line-numbers: false
#| classes: code-125

dat <- rio::import("https://fabio-setti.netlify.app/data/States_subset.csv")
```

```{r}

library(FabioFun)

labels <- c("State Name",
            "State Code",
            "Number of Airports Per State",
            "State Surface in Squared Miles",
            "Number of Inhabitants",
            "Percentage of Biden Votes in 2020",
            "Percentage of Trump Votes in 2020",
            "Percentage of Catholic Population",
            "Percentage of Non-Religious Individuals")

labels_react <- reactbl_col.desc(names = colnames(dat),
                                 desc =  labels,
                                 style = "cursor: pointer; text-decoration: none;",
                                 info_color = "#7a0b80")


reactable::reactable(dat,
                     defaultColDef = colDef(minWidth = 140),
                     style = list(fontFamily = "Work Sans, sans-serif", fontSize = "1rem"),
                     pagination = FALSE, highlight = TRUE, height = 300, columns = labels_react)
```

:::
::::



## References 

<div id="refs"> </div>